### PR TITLE
Add tflite gpu version

### PR DESCRIPTION
**Pull request by lmy931**
Hi, I really like this project, so I just add a gpu-version for tflite.
I have tried it on my Google pixel 1.
CPU: > 160 ms
GPU: 100 ms
Cheers

### CODE REVIEW

**Comment by lmy931** [comment]
This is the first time I pull a request. Should I make a new branch?

**Comment by edvardHua** [comment]
Thanks for you contribution ! But you need to create a new branch. 😁

**Comment by edvardHua** [comment]
Hi, why close PR ?

**Comment by lmy931** [comment]
I created another one. I tried to create a new branch 😁

**Pull request closed without merging**
